# Site settings
title: CMSC423 (Fall 2014)
email: hcorrada@umiacs.umd.edu
description: "CMSC423, Bioinformatics. University of Maryland, College Park. Department of Computer Science"
baseurl: "/~hcorrada/CMSC423"
url: "http://cbcb.umd.edu/~hcorrada/CMSC423"
twitter_username: hcorrada
github_username:  hcorrada

pageOrder: ["/index.html"]

# Build settings
markdown: kramdown
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# my variables
piazza_url: "https://piazza.com/class/i5e39xpjr662in"
elms_url: "https://myelms.umd.edu/courses/1130499"

